import type { RealmNumericTemplate } from '../../numeric';
import type { Attributes, BreakthroughItemRequirement } from '../../types';
import { PlayerRealmStage, TechniqueRealm } from '../../types';

import {
  BASE_HIT,
  BASE_HP_REGEN_RATE,
  BASE_MAX_HP,
  BASE_MAX_QI,
  BASE_MAX_QI_OUTPUT_PER_TICK,
  BASE_PHYS_ATK,
  BASE_PHYS_DEF,
  BASE_QI_REGEN_RATE,
  BASE_SPELL_ATK,
  BASE_SPELL_DEF,
} from './attributes';
import { VIEW_RADIUS } from './world';

/**
 * 境界成长与境界模板常量。
 */

type RealmConfig = {
  name: string;
  shortName: string;
  path: 'martial' | 'immortal';
  narrative: string;
  progressToNext: number;
  attrBonus: Partial<Attributes>;
  breakthroughItems: BreakthroughItemRequirement[];
  minTechniqueLevel: number;
  minTechniqueRealm?: TechniqueRealm;
};

const ZERO_ELEMENT_STATS = {
  metal: 0,
  wood: 0,
  water: 0,
  fire: 0,
  earth: 0,
} as const;

const FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR = 100;

/** 默认玩家大境界。 */
export const DEFAULT_PLAYER_REALM_STAGE = PlayerRealmStage.Mortal;

/** 玩家大境界顺序。 */
export const PLAYER_REALM_ORDER: PlayerRealmStage[] = [
  PlayerRealmStage.Mortal,
  PlayerRealmStage.BodyTempering,
  PlayerRealmStage.BoneForging,
  PlayerRealmStage.Meridian,
  PlayerRealmStage.Innate,
  PlayerRealmStage.QiRefining,
  PlayerRealmStage.Foundation,
];

/** 玩家大境界对应的等级区间。 */
export const PLAYER_REALM_STAGE_LEVEL_RANGES: Record<PlayerRealmStage, { levelFrom: number; levelTo: number }> = {
  [PlayerRealmStage.Mortal]: { levelFrom: 1, levelTo: 5 },
  [PlayerRealmStage.BodyTempering]: { levelFrom: 6, levelTo: 8 },
  [PlayerRealmStage.BoneForging]: { levelFrom: 9, levelTo: 12 },
  [PlayerRealmStage.Meridian]: { levelFrom: 13, levelTo: 15 },
  [PlayerRealmStage.Innate]: { levelFrom: 16, levelTo: 18 },
  [PlayerRealmStage.QiRefining]: { levelFrom: 19, levelTo: 30 },
  [PlayerRealmStage.Foundation]: { levelFrom: 31, levelTo: 42 },
};

/** 武道到修仙的大境界配置。 */
export const PLAYER_REALM_CONFIG: Record<PlayerRealmStage, RealmConfig> = {
  [PlayerRealmStage.Mortal]: {
    name: '凡俗境',
    shortName: '凡俗',
    path: 'martial',
    narrative: '筋骨未开，仍在江湖门槛之外，只能以勤练夯实根基。',
    progressToNext: 60,
    attrBonus: {},
    breakthroughItems: [
      { itemId: 'rat_tail', count: 3 },
      { itemId: 'boar_tusk', count: 1 },
    ],
    minTechniqueLevel: 1,
  },
  [PlayerRealmStage.BodyTempering]: {
    name: '炼体境',
    shortName: '炼体',
    path: 'martial',
    narrative: '气血打熬周身，筋膜初固，正式迈入武道修行。',
    progressToNext: 120,
    attrBonus: { constitution: 2, perception: 1 },
    breakthroughItems: [
      { itemId: 'wolf_fang', count: 4 },
      { itemId: 'serpent_gall', count: 2 },
    ],
    minTechniqueLevel: 2,
    minTechniqueRealm: TechniqueRealm.Entry,
  },
  [PlayerRealmStage.BoneForging]: {
    name: '锻骨境',
    shortName: '锻骨',
    path: 'martial',
    narrative: '骨骼经受药力与劲力淬炼，气血承载力显著增长。',
    progressToNext: 180,
    attrBonus: { constitution: 4, spirit: 1, perception: 2 },
    breakthroughItems: [
      { itemId: 'black_iron_chunk', count: 4 },
      { itemId: 'crystal_dust', count: 3 },
    ],
    minTechniqueLevel: 4,
    minTechniqueRealm: TechniqueRealm.Minor,
  },
  [PlayerRealmStage.Meridian]: {
    name: '通脉境',
    shortName: '通脉',
    path: 'martial',
    narrative: '经脉渐通，劲力开始带有内息性质，武道正向玄门靠拢。',
    progressToNext: 260,
    attrBonus: { constitution: 6, spirit: 2, perception: 3, comprehension: 1 },
    breakthroughItems: [
      { itemId: 'black_iron_chunk', count: 6 },
      { itemId: 'rune_shard', count: 4 },
      { itemId: 'mine_signal_core', count: 1 },
    ],
    minTechniqueLevel: 6,
    minTechniqueRealm: TechniqueRealm.Minor,
  },
  [PlayerRealmStage.Innate]: {
    name: '先天境',
    shortName: '先天',
    path: 'martial',
    narrative: '内外归一，先天一炁渐显，是凡武迈向仙道的最后门槛。',
    progressToNext: 360,
    attrBonus: { constitution: 8, spirit: 4, perception: 4, talent: 2, comprehension: 2 },
    breakthroughItems: [
      { itemId: 'rune_shard', count: 6 },
      { itemId: 'spirit_iron_fragment', count: 4 },
      { itemId: 'valley_core', count: 1 },
    ],
    minTechniqueLevel: 8,
    minTechniqueRealm: TechniqueRealm.Major,
  },
  [PlayerRealmStage.QiRefining]: {
    name: '练气境',
    shortName: '练气',
    path: 'immortal',
    narrative: '可引天地灵机入体，真正踏入修仙序列，功法威能随之跃迁。',
    progressToNext: 1040,
    attrBonus: { constitution: 10, spirit: 8, perception: 5, talent: 4, comprehension: 3, luck: 1 },
    breakthroughItems: [
      { itemId: 'blood_feather', count: 6 },
      { itemId: 'demon_wolf_bone', count: 6 },
      { itemId: 'spirit_iron_fragment', count: 6 },
    ],
    minTechniqueLevel: 10,
    minTechniqueRealm: TechniqueRealm.Major,
  },
  [PlayerRealmStage.Foundation]: {
    name: '筑基境',
    shortName: '筑基',
    path: 'immortal',
    narrative: '道基初成，体魄与灵识都进入更高层次，是后续金丹之路的正式起点。',
    progressToNext: 1240,
    attrBonus: { constitution: 14, spirit: 12, perception: 8, talent: 6, comprehension: 5, luck: 2 },
    breakthroughItems: [],
    minTechniqueLevel: 12,
    minTechniqueRealm: TechniqueRealm.Perfection,
  },
};

/** 按境界提供的具体属性基准与 RatioValue 基数。 */
export const PLAYER_REALM_NUMERIC_TEMPLATES: Record<PlayerRealmStage, RealmNumericTemplate> = {
  [PlayerRealmStage.Mortal]: {
    stage: PlayerRealmStage.Mortal,
    stats: {
      maxHp: BASE_MAX_HP,
      maxQi: BASE_MAX_QI,
      physAtk: BASE_PHYS_ATK,
      spellAtk: BASE_SPELL_ATK,
      physDef: BASE_PHYS_DEF,
      spellDef: BASE_SPELL_DEF,
      hit: BASE_HIT,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 0,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 100,
      crit: 100,
      breakPower: 100,
      resolvePower: 100,
      cooldownSpeed: 100,
      moveSpeed: 100,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.BodyTempering]: {
    stage: PlayerRealmStage.BodyTempering,
    stats: {
      maxHp: BASE_MAX_HP + 20,
      maxQi: BASE_MAX_QI,
      physAtk: BASE_PHYS_ATK + 2,
      spellAtk: BASE_SPELL_ATK,
      physDef: BASE_PHYS_DEF + 2,
      spellDef: BASE_SPELL_DEF,
      hit: BASE_HIT,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 0,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 120,
      crit: 120,
      breakPower: 120,
      resolvePower: 120,
      cooldownSpeed: 120,
      moveSpeed: 120,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.BoneForging]: {
    stage: PlayerRealmStage.BoneForging,
    stats: {
      maxHp: BASE_MAX_HP + 45,
      maxQi: BASE_MAX_QI + 10,
      physAtk: BASE_PHYS_ATK + 4,
      spellAtk: BASE_SPELL_ATK,
      physDef: BASE_PHYS_DEF + 4,
      spellDef: BASE_SPELL_DEF + 2,
      hit: BASE_HIT,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK + 2,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 0,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 150,
      crit: 150,
      breakPower: 150,
      resolvePower: 150,
      cooldownSpeed: 150,
      moveSpeed: 150,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.Meridian]: {
    stage: PlayerRealmStage.Meridian,
    stats: {
      maxHp: BASE_MAX_HP + 80,
      maxQi: BASE_MAX_QI + 25,
      physAtk: BASE_PHYS_ATK + 6,
      spellAtk: BASE_SPELL_ATK + 4,
      physDef: BASE_PHYS_DEF + 6,
      spellDef: BASE_SPELL_DEF + 5,
      hit: BASE_HIT + 4,
      dodge: 0,
      crit: 0,
      antiCrit: 0,
      critDamage: 0,
      breakPower: 0,
      resolvePower: 0,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK + 4,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 4,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 190,
      crit: 190,
      breakPower: 190,
      resolvePower: 190,
      cooldownSpeed: 190,
      moveSpeed: 190,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.Innate]: {
    stage: PlayerRealmStage.Innate,
    stats: {
      maxHp: BASE_MAX_HP + 130,
      maxQi: BASE_MAX_QI + 45,
      physAtk: BASE_PHYS_ATK + 10,
      spellAtk: BASE_SPELL_ATK + 8,
      physDef: BASE_PHYS_DEF + 10,
      spellDef: BASE_SPELL_DEF + 8,
      hit: BASE_HIT + 8,
      dodge: 4,
      crit: 4,
      antiCrit: 4,
      critDamage: 0,
      breakPower: 4,
      resolvePower: 4,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK + 8,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 8,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 240,
      crit: 240,
      breakPower: 240,
      resolvePower: 240,
      cooldownSpeed: 240,
      moveSpeed: 240,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.QiRefining]: {
    stage: PlayerRealmStage.QiRefining,
    stats: {
      maxHp: BASE_MAX_HP + 190,
      maxQi: BASE_MAX_QI + 90,
      physAtk: BASE_PHYS_ATK + 14,
      spellAtk: BASE_SPELL_ATK + 16,
      physDef: BASE_PHYS_DEF + 14,
      spellDef: BASE_SPELL_DEF + 15,
      hit: BASE_HIT + 12,
      dodge: 6,
      crit: 6,
      antiCrit: 6,
      critDamage: 100,
      breakPower: 6,
      resolvePower: 6,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK + 14,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 12,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 300,
      crit: 300,
      breakPower: 300,
      resolvePower: 300,
      cooldownSpeed: 300,
      moveSpeed: 300,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
  [PlayerRealmStage.Foundation]: {
    stage: PlayerRealmStage.Foundation,
    stats: {
      maxHp: BASE_MAX_HP + 270,
      maxQi: BASE_MAX_QI + 150,
      physAtk: BASE_PHYS_ATK + 22,
      spellAtk: BASE_SPELL_ATK + 24,
      physDef: BASE_PHYS_DEF + 22,
      spellDef: BASE_SPELL_DEF + 22,
      hit: BASE_HIT + 18,
      dodge: 10,
      crit: 10,
      antiCrit: 10,
      critDamage: 200,
      breakPower: 10,
      resolvePower: 10,
      maxQiOutputPerTick: BASE_MAX_QI_OUTPUT_PER_TICK + 24,
      qiRegenRate: BASE_QI_REGEN_RATE,
      hpRegenRate: BASE_HP_REGEN_RATE,
      cooldownSpeed: 18,
      auraCostReduce: 0,
      auraPowerRate: 0,
      playerExpRate: 0,
      techniqueExpRate: 0,
      realmExpPerTick: 0,
      techniqueExpPerTick: 0,
      lootRate: 0,
      rareLootRate: 0,
      viewRange: VIEW_RADIUS + 1,
      moveSpeed: 0,
      extraAggroRate: 0,
      extraRange: 0,
      extraArea: 0,
      elementDamageBonus: { ...ZERO_ELEMENT_STATS },
      elementDamageReduce: { ...ZERO_ELEMENT_STATS },
    },
    ratioDivisors: {
      dodge: 380,
      crit: 380,
      breakPower: 380,
      resolvePower: 380,
      cooldownSpeed: 380,
      moveSpeed: 380,
      elementDamageReduce: {
        metal: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        wood: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        water: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        fire: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
        earth: FIXED_ELEMENT_DAMAGE_REDUCE_DIVISOR,
      },
    },
  },
};
