/**
 * 客户端新手导览配置。
 *
 * 这里描述全系统操作引导（核心操作、战斗引导、技艺引导、玩法引导）的步骤与交互，
 * 具体遮罩和定位由 ui/guided-tour.ts 负责。
 */

export type GuidedTourPlacement = 'auto' | 'top' | 'right' | 'bottom' | 'left';

export type GuidedTourAdvanceMode = 'next' | 'target-click';

export type GuidedTourPrepareWhen = 'always' | 'mobile' | 'desktop';

export type GuidedTourCategory = 'core' | 'combat' | 'craft' | 'gameplay';

export interface GuidedTourCategoryMeta {
  id: GuidedTourCategory;
  label: string;
  desc: string;
}

export const GUIDED_TOUR_CATEGORY_METAS: GuidedTourCategoryMeta[] = [
  { id: 'core', label: '核心操作', desc: '界面视野、任务寻路、装备、功法修炼、采集搜箱、突破与炼体等日常操作。' },
  { id: 'combat', label: '战斗引导', desc: '锁定目标、强制攻击、技能管理、自动施法循环与自动吃药保命配置。' },
  { id: 'craft', label: '技艺引导', desc: '破障采矿、炼丹开炉、炼器锻造、装备强化防爆与建筑营造。' },
  { id: 'gameplay', label: '玩法引导', desc: '通天塔挑战、开天门灵根觉醒、筑基道基初誓、法宝巡天飞行与宗门领地。' },
];

export type GuidedTourPrepareAction =
  | {
      type: 'switch-tab';
      tabName: string;
      when?: GuidedTourPrepareWhen;
    }
  | {
      type: 'set-layout-collapsed';
      target: 'left' | 'right' | 'bottom';
      collapsed: boolean;
      when?: GuidedTourPrepareWhen;
    }
  | {
      type: 'click';
      selector: string;
      mobileSelector?: string;
      waitMs?: number;
      when?: GuidedTourPrepareWhen;
    };

export interface GuidedTourStep {
  id: string;
  targetSelector: string;
  mobileTargetSelector?: string;
  titleKey: string;
  titleFallback: string;
  bodyKey: string;
  bodyFallback: string;
  placement?: GuidedTourPlacement;
  advanceMode?: GuidedTourAdvanceMode;
  prepare?: GuidedTourPrepareAction[];
}

export interface GuidedTourFlow {
  id: string;
  category: GuidedTourCategory;
  storageVersion: number;
  autoStart: boolean;
  titleKey: string;
  titleFallback: string;
  summaryKey?: string;
  summaryFallback?: string;
  steps: GuidedTourStep[];
}

export const STARTER_GUIDED_TOUR_FLOW_ID = 'starter-basics';

// ─── 常用 prepareAction 辅助定义 ───────────────────────────────────────────────

const OPEN_ACTION_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  { type: 'set-layout-collapsed', target: 'right', collapsed: false, when: 'desktop' },
  { type: 'switch-tab', tabName: 'mobile-action', when: 'mobile' },
];

const OPEN_ACTION_UTILITY_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_ACTION_PANEL_PREPARE,
  { type: 'click', selector: '[data-action-tab="utility"]' },
];

const OPEN_ACTION_TOGGLE_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_ACTION_PANEL_PREPARE,
  { type: 'click', selector: '[data-action-tab="toggle"]' },
];

const OPEN_ACTION_SKILL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_ACTION_PANEL_PREPARE,
  { type: 'click', selector: '[data-action-tab="skill"]' },
];

const OPEN_BAG_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  { type: 'set-layout-collapsed', target: 'right', collapsed: false, when: 'desktop' },
  { type: 'switch-tab', tabName: 'mobile-bag', when: 'mobile' },
];

const OPEN_INVENTORY_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_BAG_PANEL_PREPARE,
  { type: 'switch-tab', tabName: 'inventory' },
];

const OPEN_EQUIPMENT_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_BAG_PANEL_PREPARE,
  { type: 'switch-tab', tabName: 'equipment' },
];

const OPEN_TECHNIQUE_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_BAG_PANEL_PREPARE,
  { type: 'switch-tab', tabName: 'technique' },
];

const OPEN_QUEST_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_BAG_PANEL_PREPARE,
  { type: 'switch-tab', tabName: 'quest' },
];

const OPEN_BODY_TRAINING_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_BAG_PANEL_PREPARE,
  { type: 'switch-tab', tabName: 'body-training' },
];

const OPEN_ATTR_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  { type: 'set-layout-collapsed', target: 'left', collapsed: false, when: 'desktop' },
  { type: 'switch-tab', tabName: 'mobile-attrs', when: 'mobile' },
];

const OPEN_ATTR_CRAFT_PANEL_PREPARE: GuidedTourPrepareAction[] = [
  ...OPEN_ATTR_PANEL_PREPARE,
  { type: 'click', selector: '[data-guided-tour-attr-tab="craft"]' },
];

// ─── 全部 25 条引导流定义 ───────────────────────────────────────────────────────

export const GUIDED_TOUR_FLOWS: GuidedTourFlow[] = [
  // ── 一、核心操作引导 (11 条) ─────────────────────────────────────────────────
  {
    id: 'starter-basics',
    category: 'core',
    storageVersion: 2,
    autoStart: true,
    titleKey: 'guided-tour.flow.starter.title',
    titleFallback: '基础界面与视野导览',
    summaryFallback: '带你熟悉角色状态条、主地图行动区、地图标记、行囊背包、行动栏与百科入口。',
    steps: [
      {
        id: 'hud',
        targetSelector: '#hud',
        titleKey: 'guided-tour.step.hud.title',
        titleFallback: '先看自身状态',
        bodyKey: 'guided-tour.step.hud.body',
        bodyFallback: '这里显示角色、境界、气血、灵力和突破入口。后续满修为能突破时，按钮会出现在境界区域。',
        placement: 'right',
        prepare: [
          { type: 'set-layout-collapsed', target: 'left', collapsed: false, when: 'desktop' },
          { type: 'switch-tab', tabName: 'mobile-overview', when: 'mobile' },
        ],
      },
      {
        id: 'map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.map.title',
        titleFallback: '地图是主要行动区',
        bodyKey: 'guided-tour.step.map.body',
        bodyFallback: '点击可见地图格子可以自动移动或选择目标。战斗、采集、观察等指向性操作也会落在这里。',
        placement: 'top',
        prepare: [
          { type: 'set-layout-collapsed', target: 'bottom', collapsed: false, when: 'desktop' },
        ],
      },
      {
        id: 'map-icons',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.map-icons.title',
        titleFallback: '看懂地图标记',
        bodyKey: 'guided-tour.step.map-icons.body',
        bodyFallback: 'NPC 头顶标记中，! 表示可接任务，? 表示可交付，... 表示进行中。传送点用于跨地图，草药矿脉可采集，红名怪物为敌对。',
        placement: 'top',
      },
      {
        id: 'inventory-tab',
        targetSelector: '[data-tab="inventory"]',
        mobileTargetSelector: '[data-tab="mobile-bag"]',
        titleKey: 'guided-tour.step.inventory.title',
        titleFallback: '打开行囊',
        bodyKey: 'guided-tour.step.inventory.body',
        bodyFallback: '背包、装备、功法和任务都在这一侧。点击高亮按钮进入行囊页签。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: [
          { type: 'set-layout-collapsed', target: 'right', collapsed: false, when: 'desktop' },
        ],
      },
      {
        id: 'action-panel',
        targetSelector: '#pane-action',
        titleKey: 'guided-tour.step.action.title',
        titleFallback: '行动栏执行操作',
        bodyKey: 'guided-tour.step.action.body',
        bodyFallback: '常用互动、技能、开关和通用操作都在行动栏。需要点目标的操作会先进入选格状态，再到地图上点选。',
        placement: 'left',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'tutorial-book',
        targetSelector: '#hud-open-tutorial',
        titleKey: 'guided-tour.step.tutorial.title',
        titleFallback: '百科随时可查',
        bodyKey: 'guided-tour.step.tutorial.body',
        bodyFallback: '不清楚系统规则时，可以随时从左上角打开百科查阅，支持全文搜索。',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'quest-navigation-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.quest-nav.title',
    titleFallback: '任务接取与寻路引导',
    summaryFallback: '掌握任务面板查看、一键跨图寻路以及靠近 NPC 交互交付。',
    steps: [
      {
        id: 'quest-tab',
        targetSelector: '[data-tab="quest"]',
        mobileTargetSelector: '[data-tab="quest"]',
        titleKey: 'guided-tour.step.quest-tab.title',
        titleFallback: '进入任务面板',
        bodyKey: 'guided-tour.step.quest-tab.body',
        bodyFallback: '在右侧行囊侧栏中选择「任务」页签，查看当前所有主线、支线与日常任务。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_QUEST_PANEL_PREPARE,
      },
      {
        id: 'quest-card',
        targetSelector: '.quest-item, [data-quest-id]' ,
        titleKey: 'guided-tour.step.quest-card.title',
        titleFallback: '查看任务详情',
        bodyKey: 'guided-tour.step.quest-card.body',
        bodyFallback: '点击任务条目可查看剧情背景、目标要求、当前进度以及完成奖励。',
        placement: 'left',
        prepare: OPEN_QUEST_PANEL_PREPARE,
      },
      {
        id: 'quest-nav-btn',
        targetSelector: '[data-quest-navigate="true"], .quest-detail-nav-btn, .quest-item, [data-quest-id], #pane-quest',
        titleKey: 'guided-tour.step.quest-nav-btn.title',
        titleFallback: '一键自动寻路',
        bodyKey: 'guided-tour.step.quest-nav-btn.body',
        bodyFallback: '点击「前往目标」或「前往交付」，角色将使用 A* 自动跨图寻路走向目标 NPC 或地点。',
        placement: 'top',
        prepare: OPEN_QUEST_PANEL_PREPARE,
      },
      {
        id: 'quest-interact',
        targetSelector: '#pane-action [data-action-tab="interaction"], [data-action-tab="interaction"], #pane-action, #game-stage',
        titleKey: 'guided-tour.step.quest-interact.title',
        titleFallback: '靠近 NPC 交付',
        bodyKey: 'guided-tour.step.quest-interact.body',
        bodyFallback: '走到 NPC 身旁 1 格内，右下角互动栏会自动出现对话与交付按钮，点击即可提交任务领取奖励。',
        placement: 'left',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
    ],
  },
  {
    id: 'equipment-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.equipment.title',
    titleFallback: '装备穿戴与属性提升',
    summaryFallback: '学习在行囊中穿戴防具武器，观察人物六维属性变化与装备品质。',
    steps: [
      {
        id: 'open-inventory',
        targetSelector: '[data-tab="inventory"]',
        mobileTargetSelector: '[data-tab="mobile-bag"]',
        titleKey: 'guided-tour.step.open-inventory.title',
        titleFallback: '打开行囊背包',
        bodyKey: 'guided-tour.step.open-inventory.body',
        bodyFallback: '完成任务或战斗掉落的装备都会放入行囊背包中。点击高亮按钮进入行囊背包。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_BAG_PANEL_PREPARE,
      },
      {
        id: 'select-equip-item',
        targetSelector: '.inventory-slot[data-item-type="equipment"], [data-inventory-slot]' ,
        titleKey: 'guided-tour.step.select-equip-item.title',
        titleFallback: '选中装备物品',
        bodyKey: 'guided-tour.step.select-equip-item.body',
        bodyFallback: '点击背包中的防具或武器，查看装备品阶、部位槽位、基础攻击防御以及六维加成。',
        placement: 'top',
        prepare: OPEN_INVENTORY_PANEL_PREPARE,
      },
      {
        id: 'equip-action-btn',
        targetSelector: '[data-item-action="equip"], [data-guided-tour-equip="true"]',
        titleKey: 'guided-tour.step.equip-action-btn.title',
        titleFallback: '点击穿戴',
        bodyKey: 'guided-tour.step.equip-action-btn.body',
        bodyFallback: '点击「穿戴」按钮将装备穿戴到武器、头部、衣服、腿部或饰品槽位。',
        placement: 'left',
        prepare: OPEN_INVENTORY_PANEL_PREPARE,
      },
      {
        id: 'check-attr-growth',
        targetSelector: '#pane-attr',
        titleKey: 'guided-tour.step.check-attr-growth.title',
        titleFallback: '观察属性提升',
        bodyKey: 'guided-tour.step.check-attr-growth.body',
        bodyFallback: '装备穿戴后，左侧属性卷中的气血、攻击、防御与六维数值立即获得对应加成。',
        placement: 'right',
        prepare: OPEN_ATTR_PANEL_PREPARE,
      },
    ],
  },
  {
    id: 'cultivation-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.cultivation.title',
    titleFallback: '功法领悟与修炼引导',
    summaryFallback: '掌握学习功法秘籍、设为主修功法、开启闭关修炼与空闲自动修炼。',
    steps: [
      {
        id: 'cultivation-open-bag',
        targetSelector: '[data-tab="inventory"]',
        mobileTargetSelector: '[data-tab="mobile-bag"]',
        titleKey: 'guided-tour.step.cultivation-open-bag.title',
        titleFallback: '打开行囊侧栏',
        bodyKey: 'guided-tour.step.cultivation-open-bag.body',
        bodyFallback: '功法面板在行囊侧栏里。桌面端展开右侧，手机端先切到行囊页。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_BAG_PANEL_PREPARE,
      },
      {
        id: 'cultivation-technique-tab',
        targetSelector: '[data-tab="technique"]',
        titleKey: 'guided-tour.step.cultivation-technique-tab.title',
        titleFallback: '切到功法页',
        bodyKey: 'guided-tour.step.cultivation-technique-tab.body',
        bodyFallback: '修炼功法前，先进入功法页查看已学功法、领悟进度和主修按钮。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_BAG_PANEL_PREPARE,
      },
      {
        id: 'cultivation-technique-card',
        targetSelector: '[data-guided-tour-cultivate-button="true"], [data-tech-cultivate-button]',
        titleKey: 'guided-tour.step.cultivation-technique-card.title',
        titleFallback: '设为主修功法',
        bodyKey: 'guided-tour.step.cultivation-technique-card.body',
        bodyFallback: '点击功法卡片上的「设为主修」，角色修炼时获得的修为与功法经验将全部注入该功法中。',
        placement: 'left',
        prepare: OPEN_TECHNIQUE_PANEL_PREPARE,
      },
      {
        id: 'cultivation-toggle-tab',
        targetSelector: '[data-action-tab="toggle"]',
        titleKey: 'guided-tour.step.cultivation-toggle-tab.title',
        titleFallback: '切到开关面板',
        bodyKey: 'guided-tour.step.cultivation-toggle-tab.body',
        bodyFallback: '主修功法确定后，再回到行动栏开关页控制当前是否闭关修炼。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'cultivation-toggle-card',
        targetSelector: '[data-action-card="cultivation:toggle"]',
        titleKey: 'guided-tour.step.cultivation-toggle-card.title',
        titleFallback: '开启闭关修炼',
        bodyKey: 'guided-tour.step.cultivation-toggle-card.body',
        bodyFallback: '开启后角色进入闭关状态，每息稳定增长境界修为与功法层数；移动或攻击会自动打断修炼。',
        placement: 'left',
        prepare: OPEN_ACTION_TOGGLE_PREPARE,
      },
      {
        id: 'cultivation-auto-card',
        targetSelector: '[data-action-card="toggle:auto_idle_cultivation"]',
        titleKey: 'guided-tour.step.cultivation-auto-card.title',
        titleFallback: '开启空闲自动修炼',
        bodyKey: 'guided-tour.step.cultivation-auto-card.body',
        bodyFallback: '建议开启「空闲自动修炼」，角色在站立不动无战斗时会自动恢复修炼状态。',
        placement: 'left',
        prepare: OPEN_ACTION_TOGGLE_PREPARE,
      },
    ],
  },
  {
    id: 'take-interaction-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.take-interaction.title',
    titleFallback: '拿取采集与搜箱引导',
    summaryFallback: '学习使用「拿取」行动采集野外草药、搜刮宝箱容器与拾取地面掉落物。',
    steps: [
      {
        id: 'take-utility-tab',
        targetSelector: '[data-action-tab="utility"]',
        titleKey: 'guided-tour.step.take-utility-tab.title',
        titleFallback: '切到通用行动页',
        bodyKey: 'guided-tour.step.take-utility-tab.body',
        bodyFallback: '通用页放置拿取、观察、强制攻击、遁返等系统级行动。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'take-button',
        targetSelector: '[data-action-exec="loot:open"], [data-action-card="loot:open"], [data-action-row="loot:open"]',
        titleKey: 'guided-tour.step.take-button.title',
        titleFallback: '点击拿取',
        bodyKey: 'guided-tour.step.take-button.body',
        bodyFallback: '点击「拿取」后进入选格状态，光标变为拾取手势，无需提前靠近。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_UTILITY_PREPARE,
      },
      {
        id: 'take-map-target',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.take-map-target.title',
        titleFallback: '在地图上点选目标格',
        bodyKey: 'guided-tour.step.take-map-target.body',
        bodyFallback: '点击地上的药草、宝箱或掉落物格子。若是药草会自动采摘入包，若是容器会弹出检索窗口，点击全部拿取即可。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'breakthrough-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.breakthrough.title',
    titleFallback: '境界突破与底蕴积累',
    summaryFallback: '当修为攒满 100% 时，查看突破丹药条件、底蕴加成并突破至下一境界。',
    steps: [
      {
        id: 'breakthrough-hud-btn',
        targetSelector: '#hud-breakthrough, #hud-breakthrough-btn, [data-hud-breakthrough]',
        titleKey: 'guided-tour.step.breakthrough-hud-btn.title',
        titleFallback: '点击突破按钮',
        bodyKey: 'guided-tour.step.breakthrough-hud-btn.body',
        bodyFallback: '当修为进度条攒满时，HUD 境界栏右侧会出现闪烁的「突破」按钮。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'breakthrough-detail-modal',
        targetSelector: '.breakthrough-modal-grid, .breakthrough-requirements-panel, .breakthrough-modal',
        titleKey: 'guided-tour.step.breakthrough-detail-modal.title',
        titleFallback: '查看突破条件与底蕴',
        bodyKey: 'guided-tour.step.breakthrough-detail-modal.body',
        bodyFallback: '弹窗中显示突破所需的丹药材料、成功率、以及当前角色「底蕴」带来的成功率与属性加成。',
        placement: 'top',
      },
      {
        id: 'breakthrough-confirm-btn',
        targetSelector: '[data-breakthrough-confirm], .breakthrough-confirm-btn',
        titleKey: 'guided-tour.step.breakthrough-confirm-btn.title',
        titleFallback: '确认突破升阶',
        bodyKey: 'guided-tour.step.breakthrough-confirm-btn.body',
        bodyFallback: '点击确认突破，渡过气血关隘，迈入新境界，解锁更高的等级上限与新属性。',
        placement: 'top',
        advanceMode: 'target-click',
      },
    ],
  },
  {
    id: 'body-training-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.body-training.title',
    titleFallback: '炼体长线加成养成',
    summaryFallback: '了解炼体全属性百分比加成规则，在境界瓶颈时投入修为提升肉身实力。',
    steps: [
      {
        id: 'body-training-tab',
        targetSelector: '[data-tab="body-training"], [data-guided-tour-body-training]',
        titleKey: 'guided-tour.step.body-training-tab.title',
        titleFallback: '打开炼体面板',
        bodyKey: 'guided-tour.step.body-training-tab.body',
        bodyFallback: '炼体是一套长线百分比加成体系，每提升一层全六维属性永久提升 1%。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_BODY_TRAINING_PANEL_PREPARE,
      },
      {
        id: 'body-training-stats',
        targetSelector: '.body-training-stats, [data-body-training-stats]' ,
        titleKey: 'guided-tour.step.body-training-stats.title',
        titleFallback: '了解炼体收益',
        bodyKey: 'guided-tour.step.body-training-stats.body',
        bodyFallback: '在境界遇到瓶颈或修为溢出时，将多余修为与肉身药材投入炼体，是拉开综合战力的关键。',
        placement: 'right',
        prepare: OPEN_BODY_TRAINING_PANEL_PREPARE,
      },
      {
        id: 'body-training-upgrade',
        targetSelector: '[data-body-infuse="true"], .body-training-infuse-btn, [data-body-training-btn="upgrade"]',
        titleKey: 'guided-tour.step.body-training-upgrade.title',
        titleFallback: '注入修为提升',
        bodyKey: 'guided-tour.step.body-training-upgrade.body',
        bodyFallback: '消耗指定修为与材料，完成淬体沉淀。',
        placement: 'top',
        prepare: OPEN_BODY_TRAINING_PANEL_PREPARE,
      },
    ],
  },
  {
    id: 'observe-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.observe.title',
    titleFallback: '地图观察与情报探索',
    summaryFallback: '探查视野内地图格子的地块耐久、五行属性、所处建筑、怪物等级与血量。',
    steps: [
      {
        id: 'observe-action-panel',
        targetSelector: '#pane-action',
        titleKey: 'guided-tour.step.observe-action-panel.title',
        titleFallback: '打开行动栏',
        bodyKey: 'guided-tour.step.observe-action-panel.body',
        bodyFallback: '观察是指向地图格子的通用操作，先打开行动栏。',
        placement: 'left',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'observe-utility-tab',
        targetSelector: '[data-action-tab="utility"]',
        titleKey: 'guided-tour.step.observe-utility-tab.title',
        titleFallback: '切到通用页',
        bodyKey: 'guided-tour.step.observe-utility-tab.body',
        bodyFallback: '通用页放置观察、强制攻击、返回复活点等通用操作。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'observe-button',
        targetSelector: '[data-action-exec="client:observe"], [data-action-card="client:observe"], [data-action-row="client:observe"]',
        titleKey: 'guided-tour.step.observe-button.title',
        titleFallback: '点击观察',
        bodyKey: 'guided-tour.step.observe-button.body',
        bodyFallback: '点击观察后会进入选格状态，不会消耗资源。接着到地图上选择要查看的格子。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_UTILITY_PREPARE,
      },
      {
        id: 'observe-map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.observe-map.title',
        titleFallback: '在地图上选格',
        bodyKey: 'guided-tour.step.observe-map.body',
        bodyFallback: '观察可以查看视野内格子的地形、资源、建筑或实体信息。选中目标后详情会在界面弹出。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'sense-qi-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.sense-qi.title',
    titleFallback: '感气探脉与五行气机',
    summaryFallback: '开启感气开关，在地图上直观观察灵气、魔气、煞气浓度分布与灵脉地标。',
    steps: [
      {
        id: 'sense-qi-toggle-tab',
        targetSelector: '[data-action-tab="toggle"]',
        titleKey: 'guided-tour.step.sense-qi-toggle-tab.title',
        titleFallback: '切到开关页',
        bodyKey: 'guided-tour.step.sense-qi-toggle-tab.body',
        bodyFallback: '感气是显示类开关，先进入行动栏的开关页。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'sense-qi-card',
        targetSelector: '[data-action-card="sense_qi:toggle"]',
        titleKey: 'guided-tour.step.sense-qi-card.title',
        titleFallback: '开启感气',
        bodyKey: 'guided-tour.step.sense-qi-card.body',
        bodyFallback: '点击感气开关后，地图会显示可感知的灵气（青色）、魔气（紫色）、煞气（黑色）等气机线索。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_TOGGLE_PREPARE,
      },
      {
        id: 'sense-qi-map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.sense-qi-map.title',
        titleFallback: '观察地图气机',
        bodyKey: 'guided-tour.step.sense-qi-map.body',
        bodyFallback: '开启后回到地图查看气机叠层。不同地点的灵气、阵法、地块状态会影响修炼与风水。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'mail-system-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.mail.title',
    titleFallback: '邮件系统与奖励查收',
    summaryFallback: '查收系统发放的掉落、维护补偿、活动奖励与交易通知，一键领取附件。',
    steps: [
      {
        id: 'mail-entrance',
        targetSelector: '#hud-open-mail, [data-hud-mail]',
        titleKey: 'guided-tour.step.mail-entrance.title',
        titleFallback: '点击顶部邮件入口',
        bodyKey: 'guided-tour.step.mail-entrance.body',
        bodyFallback: '界面左上角快捷入口常驻邮件图标，有未读邮件时会出现提示。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'mail-list',
        targetSelector: '.mail-modal .mail-list, [data-mail-list]' ,
        titleKey: 'guided-tour.step.mail-list.title',
        titleFallback: '查看邮件列表',
        bodyKey: 'guided-tour.step.mail-list.body',
        bodyFallback: '邮件分为系统通知、活动奖励与市场交易邮件，带有附件的邮件会标注道具图标。',
        placement: 'right',
      },
      {
        id: 'mail-claim-all',
        targetSelector: '.mail-batch-row button, .mail-batch-row, [data-mail-claim-all="true"]',
        titleKey: 'guided-tour.step.mail-claim-all.title',
        titleFallback: '一键领取附件',
        bodyKey: 'guided-tour.step.mail-claim-all.body',
        bodyFallback: '点击一键领取，所有邮件中的灵石与道具附件将自动合入背包。',
        placement: 'top',
        advanceMode: 'target-click',
      },
    ],
  },
  {
    id: 'market-guide',
    category: 'core',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.market.title',
    titleFallback: '坊市挂单与求购交易',
    summaryFallback: '学习在坊市市场挂售不绑定物品、发布灵石求购单与价格档位规则。',
    steps: [
      {
        id: 'market-entrance',
        targetSelector: '[data-tab="market"], [data-pane="market"], #pane-market',
        titleKey: 'guided-tour.step.market-entrance.title',
        titleFallback: '进入坊市',
        bodyKey: 'guided-tour.step.market-entrance.body',
        bodyFallback: '点击左上角「坊市」或行动栏快捷入口打开自由交易市场。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'market-browse',
        targetSelector: '#pane-market, [data-pane="market"], .market-tab-bar',
        titleKey: 'guided-tour.step.market-browse.title',
        titleFallback: '浏览市场挂售',
        bodyKey: 'guided-tour.step.market-browse.body',
        bodyFallback: '市场采用灵石结算与价格档位机制，买卖双方按价格优先自动撮合成交，信息匿名。',
        placement: 'left',
      },
      {
        id: 'market-sell-btn',
        targetSelector: '#pane-market button, #pane-market',
        titleKey: 'guided-tour.step.market-sell-btn.title',
        titleFallback: '挂售背包闲置道具',
        bodyKey: 'guided-tour.step.market-sell-btn.body',
        bodyFallback: '选择背包中的不绑定装备或材料，按推荐档位设定单价与数量即可上架。',
        placement: 'top',
      },
      {
        id: 'market-buy-order',
        targetSelector: '#pane-market, [data-pane="market"]',
        titleKey: 'guided-tour.step.market-buy-order.title',
        titleFallback: '发布求购单',
        bodyKey: 'guided-tour.step.market-buy-order.body',
        bodyFallback: '急需某样材料时可预冻结灵石发布求购，其他玩家出售时将自动成交并邮件派发。',
        placement: 'top',
      },
    ],
  },

  // ── 二、战斗引导 (3 条) ───────────────────────────────────────────────────
  {
    id: 'force-attack-guide',
    category: 'combat',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.force-attack.title',
    titleFallback: '目标锁定与强制攻击',
    summaryFallback: '学习在地图上手动锁定指定红名敌人或障碍物，发起强制攻击。',
    steps: [
      {
        id: 'force-attack-utility-tab',
        targetSelector: '[data-action-tab="utility"]',
        titleKey: 'guided-tour.step.force-attack-utility-tab.title',
        titleFallback: '切到通用页',
        bodyKey: 'guided-tour.step.force-attack-utility-tab.body',
        bodyFallback: '强制攻击属于通用操作，用于主动选择目标发起攻击。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'force-attack-button',
        targetSelector: '[data-action-exec="battle:force_attack"], [data-action-card="battle:force_attack"], [data-action-row="battle:force_attack"]',
        titleKey: 'guided-tour.step.force-attack-button.title',
        titleFallback: '点击强制攻击',
        bodyKey: 'guided-tour.step.force-attack-button.body',
        bodyFallback: '点击后进入选目标状态。它不会自动找怪，需要你在地图上指定要攻击的目标。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_UTILITY_PREPARE,
      },
      {
        id: 'force-attack-map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.force-attack-map.title',
        titleFallback: '选择攻击目标',
        bodyKey: 'guided-tour.step.force-attack-map.body',
        bodyFallback: '在地图上点击视野内红名怪物或障碍物即可发起攻击，开始战斗结算。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'combat-settings-guide',
    category: 'combat',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.combat-settings.title',
    titleFallback: '技能配置与自动挂机',
    summaryFallback: '掌握技能管理开启自动施法顺序、开启自动战斗与设置索敌优先级。',
    steps: [
      {
        id: 'combat-skill-tab',
        targetSelector: '[data-action-tab="skill"]',
        titleKey: 'guided-tour.step.combat-skill-tab.title',
        titleFallback: '进入技能页',
        bodyKey: 'guided-tour.step.combat-skill-tab.body',
        bodyFallback: '行动栏的技能页汇集了当前学会的全部战斗技能。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'open-skill-mgr',
        targetSelector: '[data-action-skill-manage-open], [data-action-exec="client:skill_management"]',
        titleKey: 'guided-tour.step.open-skill-mgr.title',
        titleFallback: '打开技能管理',
        bodyKey: 'guided-tour.step.open-skill-mgr.body',
        bodyFallback: '点击技能管理，进入技能自动化启用与循环施法配置界面。',
        placement: 'top',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_SKILL_PREPARE,
      },
      {
        id: 'config-auto-skill',
        targetSelector: '.skill-management-modal .skill-list, [data-skill-mgmt-list]' ,
        titleKey: 'guided-tour.step.config-auto-skill.title',
        titleFallback: '配置自动施法循环',
        bodyKey: 'guided-tour.step.config-auto-skill.body',
        bodyFallback: '勾选启用的战斗技能并调整施法顺序。冷却就绪且灵力充足时角色将按序自动释放。',
        placement: 'left',
      },
      {
        id: 'toggle-auto-battle',
        targetSelector: '[data-action-card="toggle:auto_battle"]',
        titleKey: 'guided-tour.step.toggle-auto-battle.title',
        titleFallback: '开启自动战斗',
        bodyKey: 'guided-tour.step.toggle-auto-battle.body',
        bodyFallback: '开启后角色会自动索敌并攻击视野内敌人；配合「锁敌方案」可设定优先攻击 Boss 或最近目标。',
        placement: 'left',
        prepare: OPEN_ACTION_TOGGLE_PREPARE,
      },
    ],
  },
  {
    id: 'auto-potion-guide',
    category: 'combat',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.auto-potion.title',
    titleFallback: '自动吃药恢复设置',
    summaryFallback: '在战斗设置中配置气血与灵力回复药槽，设定低血量自动服药阈值。',
    steps: [
      {
        id: 'open-combat-settings',
        targetSelector: '[data-action-combat-settings-open], [data-action-exec="client:combat_settings"]',
        titleKey: 'guided-tour.step.open-combat-settings.title',
        titleFallback: '打开战斗设置',
        bodyKey: 'guided-tour.step.open-combat-settings.body',
        bodyFallback: '点击行动栏中的战斗设置，进入自动药品与索敌策略配置。',
        placement: 'top',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_SKILL_PREPARE,
      },
      {
        id: 'equip-heal-potion',
        targetSelector: '[data-auto-pill-slot="0"], .auto-pill-slot, [data-potion-slot="hp"]',
        titleKey: 'guided-tour.step.equip-heal-potion.title',
        titleFallback: '配置气血回复药槽',
        bodyKey: 'guided-tour.step.equip-heal-potion.body',
        bodyFallback: '将回春散放入药槽，并拉动滑块设定血量低于 50% 时自动服用，防止野外战斗猝死。',
        placement: 'left',
      },
      {
        id: 'equip-qi-potion',
        targetSelector: '[data-auto-pill-slot="1"], .auto-pill-slot, [data-potion-slot="mp"]',
        titleKey: 'guided-tour.step.equip-qi-potion.title',
        titleFallback: '配置灵力回复药槽',
        bodyKey: 'guided-tour.step.equip-qi-potion.body',
        bodyFallback: '将小还灵丹放入灵力药槽，保证持续施放高阶技能时灵力不会枯竭。',
        placement: 'left',
      },
    ],
  },

  // ── 三、技艺引导 (5 条) ───────────────────────────────────────────────────
  {
    id: 'mining-guide',
    category: 'craft',
    storageVersion: 2,
    autoStart: false,
    titleKey: 'guided-tour.flow.mining.title',
    titleFallback: '障碍破坏与采矿引导',
    summaryFallback: '击碎挡路石障，进入地下矿洞，靠近矿脉采集玄铁矿石与提升采矿经验。',
    steps: [
      {
        id: 'mining-quest-tab',
        targetSelector: '[data-tab="quest"]',
        mobileTargetSelector: '[data-tab="quest"]',
        titleKey: 'guided-tour.step.mining-quest-tab.title',
        titleFallback: '从任务定位入口',
        bodyKey: 'guided-tour.step.mining-quest-tab.body',
        bodyFallback: '任务详情里会出现前往目标。本引导以云来镇旧屋矿窖演示采矿全流程。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_QUEST_PANEL_PREPARE,
      },
      {
        id: 'mining-town-entrance',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.mining-town-entrance.title',
        titleFallback: '到达矿井门前',
        bodyKey: 'guided-tour.step.mining-town-entrance.body',
        bodyFallback: '移动到云来镇旧屋矿窖入口附近。如果门口石头挡住路线，先在地图上选中石头处理掉。',
        placement: 'top',
      },
      {
        id: 'mining-clear-stone',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.mining-clear-stone.title',
        titleFallback: '击碎挡路石障',
        bodyKey: 'guided-tour.step.mining-clear-stone.body',
        bodyFallback: '石头属于可受损地块。选中石头后使用强制攻击打碎，路线才会打开。',
        placement: 'top',
      },
      {
        id: 'mining-use-portal',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.mining-use-portal.title',
        titleFallback: '踩上传送楼梯',
        bodyKey: 'guided-tour.step.mining-use-portal.body',
        bodyFallback: '走入传送点进入地下矿洞实例。',
        placement: 'top',
      },
      {
        id: 'mining-basement-node',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.mining-basement-node.title',
        titleFallback: '靠近玄铁矿脉',
        bodyKey: 'guided-tour.step.mining-basement-node.body',
        bodyFallback: '移动到玄铁矿脉 1 格范围内。采矿行动只会在附近存在矿脉时出现。',
        placement: 'top',
      },
      {
        id: 'mining-skill-tab',
        targetSelector: '[data-action-tab="skill"]',
        titleKey: 'guided-tour.step.mining-skill-tab.title',
        titleFallback: '切到技能页',
        bodyKey: 'guided-tour.step.mining-skill-tab.body',
        bodyFallback: '进入行动栏技能页，准备发起采矿行动。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_PANEL_PREPARE,
      },
      {
        id: 'mining-button',
        targetSelector: '[data-action-exec="mining:start"], [data-action-card="mining:start"], [data-action-row="mining:start"]',
        titleKey: 'guided-tour.step.mining-button.title',
        titleFallback: '点击采矿',
        bodyKey: 'guided-tour.step.mining-button.body',
        bodyFallback: '点击采矿进入矿脉选择状态，接着在地图上点选矿脉开始采集。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_SKILL_PREPARE,
      },
      {
        id: 'mining-map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.mining-map.title',
        titleFallback: '选定矿脉格',
        bodyKey: 'guided-tour.step.mining-map.body',
        bodyFallback: '在地图上点击玄铁矿脉格，角色开始开采并产出矿石与技艺经验。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'alchemy-guide',
    category: 'craft',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.alchemy.title',
    titleFallback: '炼丹开炉与配方调配',
    summaryFallback: '掌握炼丹台操作、阶段与分类筛选、五行匹配度调整、基础配方与自定义丹方。',
    steps: [
      {
        id: 'alchemy-attr-panel',
        targetSelector: '#pane-attr',
        titleKey: 'guided-tour.step.alchemy-attr-panel.title',
        titleFallback: '看左侧修行卷',
        bodyKey: 'guided-tour.step.alchemy-attr-panel.body',
        bodyFallback: '炼丹入口在左侧修行卷的技艺页里。',
        placement: 'right',
        prepare: OPEN_ATTR_PANEL_PREPARE,
      },
      {
        id: 'alchemy-craft-tab',
        targetSelector: '[data-guided-tour-attr-tab="craft"]',
        titleKey: 'guided-tour.step.alchemy-craft-tab.title',
        titleFallback: '切换到技艺',
        bodyKey: 'guided-tour.step.alchemy-craft-tab.body',
        bodyFallback: '点击技艺页，进入炼丹、炼器、强化、挖矿等技艺等级与入口列表。',
        placement: 'bottom',
        advanceMode: 'target-click',
        prepare: OPEN_ATTR_PANEL_PREPARE,
      },
      {
        id: 'alchemy-craft-row',
        targetSelector: '[data-guided-tour-craft-skill="alchemy"]',
        titleKey: 'guided-tour.step.alchemy-craft-row.title',
        titleFallback: '找到炼丹',
        bodyKey: 'guided-tour.step.alchemy-craft-row.body',
        bodyFallback: '这一行显示炼丹等级、经验进度。右侧打开按钮会进入炼丹操作界面。',
        placement: 'right',
        prepare: OPEN_ATTR_CRAFT_PANEL_PREPARE,
      },
      {
        id: 'alchemy-open',
        targetSelector: '[data-guided-tour-craft-open="alchemy"]',
        titleKey: 'guided-tour.step.alchemy-open.title',
        titleFallback: '打开炼丹台',
        bodyKey: 'guided-tour.step.alchemy-open.body',
        bodyFallback: '点击打开按钮，进入对应的炼丹操作界面。',
        placement: 'right',
        advanceMode: 'target-click',
        prepare: OPEN_ATTR_CRAFT_PANEL_PREPARE,
      },
      {
        id: 'alchemy-mortal-realm',
        targetSelector: '[data-guided-tour-alchemy-realm="mortal"]',
        titleKey: 'guided-tour.step.alchemy-mortal-realm.title',
        titleFallback: '选择凡胎阶段',
        bodyKey: 'guided-tour.step.alchemy-mortal-realm.body',
        bodyFallback: '先按丹药适用阶段筛选。回春散是凡胎阶段的基础恢复丹药，点击凡胎分组。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'alchemy-recovery-category',
        targetSelector: '[data-guided-tour-alchemy-category="recovery"]',
        titleKey: 'guided-tour.step.alchemy-recovery-category.title',
        titleFallback: '选择回复药',
        bodyKey: 'guided-tour.step.alchemy-recovery-category.body',
        bodyFallback: '再按用途筛选。回复药分组会收束到气血、灵力等恢复类丹药。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'alchemy-minor-heal',
        targetSelector: '[data-guided-tour-alchemy-output="pill.minor_heal"], [data-guided-tour-alchemy-recipe="alchemy.pill.minor_heal"]',
        titleKey: 'guided-tour.step.alchemy-minor-heal.title',
        titleFallback: '选定回春散',
        bodyKey: 'guided-tour.step.alchemy-minor-heal.body',
        bodyFallback: '点击回春散后，右侧显示五行匹配、材料、耗时、成功率和单批产出（一炉6颗）。',
        placement: 'right',
        advanceMode: 'target-click',
      },
      {
        id: 'alchemy-start',
        targetSelector: '[data-guided-tour-alchemy-start="full"]',
        titleKey: 'guided-tour.step.alchemy-start.title',
        titleFallback: '开始炼制',
        bodyKey: 'guided-tour.step.alchemy-start.body',
        bodyFallback: '材料足够时点击开始炼制，进入技艺任务队列，炼成后丹药自动入包。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'craft-forge-guide',
    category: 'craft',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.craft-forge.title',
    titleFallback: '炼器锻造装备',
    summaryFallback: '掌握炼器台打造武器与防具、矿石配比与五行吻合度。',
    steps: [
      {
        id: 'open-forging-table',
        targetSelector: '[data-guided-tour-craft-open="forging"]',
        titleKey: 'guided-tour.step.open-forging-table.title',
        titleFallback: '技艺页打开炼器台',
        bodyKey: 'guided-tour.step.open-forging-table.body',
        bodyFallback: '在技艺列表中找到「炼器」，点击打开炼器锻造界面。',
        placement: 'right',
        advanceMode: 'target-click',
        prepare: OPEN_ATTR_CRAFT_PANEL_PREPARE,
      },
      {
        id: 'select-recipe',
        targetSelector: '.recipe-list-item, [data-forging-recipe]' ,
        titleKey: 'guided-tour.step.select-recipe.title',
        titleFallback: '选择装备图谱',
        bodyKey: 'guided-tour.step.select-recipe.body',
        bodyFallback: '选择要锻造的武器或防具图谱。炼器每成功一次产出 1 件装备成品。',
        placement: 'left',
        advanceMode: 'target-click',
      },
      {
        id: 'match-elements',
        targetSelector: '[data-craft-ingredients="true"]',
        titleKey: 'guided-tour.step.match-elements.title',
        titleFallback: '投入矿石配比',
        bodyKey: 'guided-tour.step.match-elements.body',
        bodyFallback: '加入主矿与辅材，观察五行吻合度与成功率预估。',
        placement: 'left',
      },
      {
        id: 'start-forging',
        targetSelector: '[data-craft-start="true"]',
        titleKey: 'guided-tour.step.start-forging.title',
        titleFallback: '开始锻造',
        bodyKey: 'guided-tour.step.start-forging.body',
        bodyFallback: '点击开始打造玄铁装备。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'refine-equipment-guide',
    category: 'craft',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.refine-equipment.title',
    titleFallback: '装备强化与防爆机制',
    summaryFallback: '掌握装备强化等级提升、属性递增倍率以及保护材料防降级机制。',
    steps: [
      {
        id: 'open-refining-table',
        targetSelector: '[data-guided-tour-craft-open="refining"]',
        titleKey: 'guided-tour.step.open-refining-table.title',
        titleFallback: '技艺页打开强化台',
        bodyKey: 'guided-tour.step.open-refining-table.body',
        bodyFallback: '在技艺列表中找到「强化」，点击打开装备强化台。',
        placement: 'right',
        advanceMode: 'target-click',
        prepare: OPEN_ATTR_CRAFT_PANEL_PREPARE,
      },
      {
        id: 'insert-equip-and-stone',
        targetSelector: '.refine-slot-equip, .refine-slot-stone, [data-refine-equip-slot]' ,
        titleKey: 'guided-tour.step.insert-equip-and-stone.title',
        titleFallback: '放入装备与强化石',
        bodyKey: 'guided-tour.step.insert-equip-and-stone.body',
        bodyFallback: '每次成功等级 +1，属性按 ×1.1 复合递增；+1~+10 成功率高，+11 以上衰减。',
        placement: 'left',
      },
      {
        id: 'explain-protection',
        targetSelector: '.refine-slot-protect, [data-refine-protection]' ,
        titleKey: 'guided-tour.step.explain-protection.title',
        titleFallback: '保护材料说明',
        bodyKey: 'guided-tour.step.explain-protection.body',
        bodyFallback: '强化失败若无保护材料会直接归零；使用「强化保护符」失败则只降 1 级。',
        placement: 'left',
      },
      {
        id: 'start-refine',
        targetSelector: '[data-refine-start="true"]',
        titleKey: 'guided-tour.step.start-refine.title',
        titleFallback: '执行强化',
        bodyKey: 'guided-tour.step.start-refine.body',
        bodyFallback: '确认成功率与材料无误后，点击开始强化。',
        placement: 'top',
        advanceMode: 'target-click',
      },
    ],
  },
  {
    id: 'building-guide',
    category: 'craft',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.building.title',
    titleFallback: '建筑放置与施工推进',
    summaryFallback: '了解地块 5 层结构，在地图上放置半成品建筑并在 1 格内施工推进。',
    steps: [
      {
        id: 'open-building-table',
        targetSelector: '[data-guided-tour-craft-open="building"]',
        titleKey: 'guided-tour.step.open-building-table.title',
        titleFallback: '打开建造台',
        bodyKey: 'guided-tour.step.open-building-table.body',
        bodyFallback: '在技艺列表中打开建造管理。',
        placement: 'right',
        advanceMode: 'target-click',
        prepare: OPEN_ATTR_CRAFT_PANEL_PREPARE,
      },
      {
        id: 'select-structure-layer',
        targetSelector: '[data-building-layer="structure"], [data-building-layer="floor"]',
        titleKey: 'guided-tour.step.select-structure-layer.title',
        titleFallback: '选择结构层与建筑',
        bodyKey: 'guided-tour.step.select-structure-layer.body',
        bodyFallback: '地块支持 5 层结构（结构/地板/设施/家具/装饰），墙门围合后系统自动识别为房间。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'place-blueprint-map',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.place-blueprint-map.title',
        titleFallback: '在地图上选格放置',
        bodyKey: 'guided-tour.step.place-blueprint-map.body',
        bodyFallback: '在地图目标地块放置半成品建筑。',
        placement: 'top',
      },
      {
        id: 'construct-near-tile',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.construct-near-tile.title',
        titleFallback: '站立在 1 格内施工',
        bodyKey: 'guided-tour.step.construct-near-tile.body',
        bodyFallback: '守在半成品 1 格范围内才会推进施工，离开则进入休眠。',
        placement: 'top',
      },
    ],
  },

  // ── 四、玩法引导 (6 条) ───────────────────────────────────────────────────
  {
    id: 'tower-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.tower.title',
    titleFallback: '通天塔无尽挑战',
    summaryFallback: '前往栖真渡通天塔挑战无尽层数、波次清怪开宝箱与进度存档机制。',
    steps: [
      {
        id: 'tower-entrance',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.tower-entrance.title',
        titleFallback: '走向通天塔入口',
        bodyKey: 'guided-tour.step.tower-entrance.body',
        bodyFallback: '通天塔入口位于栖真渡，走到入口 1 格内点击交互即可进入。',
        placement: 'top',
      },
      {
        id: 'tower-mechanics',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.tower-mechanics.title',
        titleFallback: '了解爬塔与波次规则',
        bodyKey: 'guided-tour.step.tower-mechanics.body',
        bodyFallback: '怪物等级等于当前层数。清空本层所有波次怪后解锁通往上一层的去路。',
        placement: 'top',
      },
      {
        id: 'tower-loot-chest',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.tower-loot-chest.title',
        titleFallback: '开启通关宝箱',
        bodyKey: 'guided-tour.step.tower-loot-chest.body',
        bodyFallback: '通关每层后刷新宝箱，内含试炼古币与珍稀秘宝。',
        placement: 'top',
      },
      {
        id: 'tower-persistence',
        targetSelector: '#hud',
        titleKey: 'guided-tour.step.tower-persistence.title',
        titleFallback: '副本存档与重连',
        bodyKey: 'guided-tour.step.tower-persistence.body',
        bodyFallback: '副本持久化保存进度，离开或掉线 1 小时内返回可继续挑战。',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'open-gate-spirit-root-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.open-gate.title',
    titleFallback: '开天门·灵根觉醒',
    summaryFallback: '先天大圆满叩开天门，突破至练气期（Lv.19），觉醒五行灵根与灵气吸收加成。',
    steps: [
      {
        id: 'mortal-climax',
        targetSelector: '#hud-breakthrough, #hud-breakthrough-btn',
        titleKey: 'guided-tour.step.mortal-climax.title',
        titleFallback: '凡人期终结',
        bodyKey: 'guided-tour.step.mortal-climax.body',
        bodyFallback: '先天大圆满即为凡人极境，突破练气期将触发「开天门」质变。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'spirit-root-awakening',
        targetSelector: '.breakthrough-modal, .spirit-root-display' ,
        titleKey: 'guided-tour.step.spirit-root-awakening.title',
        titleFallback: '觉醒五行灵根',
        bodyKey: 'guided-tour.step.spirit-root-awakening.body',
        bodyFallback: '开天门将随机觉醒金木水火土灵根。单系灵根数值越高，对应属性伤害与吸收灵气效率越强。',
        placement: 'top',
      },
      {
        id: 'view-spirit-pulse',
        targetSelector: '#pane-attr',
        titleKey: 'guided-tour.step.view-spirit-pulse.title',
        titleFallback: '查看灵脉加成',
        bodyKey: 'guided-tour.step.view-spirit-pulse.body',
        bodyFallback: '在属性面板中查看五行伤害加成、减免倍率与五行灵气吸收效率。',
        placement: 'right',
        prepare: OPEN_ATTR_PANEL_PREPARE,
      },
    ],
  },
  {
    id: 'foundation-oath-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.foundation-oath.title',
    titleFallback: '筑基·道基初誓',
    summaryFallback: '服用筑基丹突破至筑基期（Lv.31），立下大道初誓，彻底开启宗门与高阶玩法。',
    steps: [
      {
        id: 'take-foundation-pill',
        targetSelector: '.inventory-slot[data-item-id="pill.foundation_elixir"], [data-inventory-slot]' ,
        titleKey: 'guided-tour.step.take-foundation-pill.title',
        titleFallback: '服用筑基丹',
        bodyKey: 'guided-tour.step.take-foundation-pill.body',
        bodyFallback: '筑基丹护持经脉，稳固道基。',
        placement: 'top',
        prepare: OPEN_INVENTORY_PANEL_PREPARE,
      },
      {
        id: 'foundation-oath-select',
        targetSelector: '#hud-breakthrough, #hud',
        titleKey: 'guided-tour.step.foundation-oath-select.title',
        titleFallback: '立下大道初誓',
        bodyKey: 'guided-tour.step.foundation-oath-select.body',
        bodyFallback: '选择自身的大道道基方向（剑修/体魄/五行道法/长生），确定后续元婴合体期的核心加成。',
        placement: 'top',
      },
      {
        id: 'unlock-advanced-systems',
        targetSelector: '[data-action-card="sect:manage"], [data-action-exec="sect:manage"], #pane-action',
        titleKey: 'guided-tour.step.unlock-advanced-systems.title',
        titleFallback: '开启宗门与高阶玩法',
        bodyKey: 'guided-tour.step.unlock-advanced-systems.body',
        bodyFallback: '筑基功成，彻底脱离散修阶段，正式解锁宗门创建、领地开拓与高阶秘境。',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'artifact-fly-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.artifact-fly.title',
    titleFallback: '法宝启用·巡天飞行',
    summaryFallback: '佩戴巡天飞剑法宝，了解每息灵力消耗与盈能机制，无视静态障碍穿行。',
    steps: [
      {
        id: 'equip-artifact',
        targetSelector: '[data-tab="equipment"] .slot-artifact, [data-tab="equipment"]',
        titleKey: 'guided-tour.step.equip-artifact.title',
        titleFallback: '佩戴巡天飞剑法宝',
        bodyKey: 'guided-tour.step.equip-artifact.body',
        bodyFallback: '在装备栏的法宝槽位佩戴巡天飞剑。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_EQUIPMENT_PANEL_PREPARE,
      },
      {
        id: 'enable-artifact-toggle',
        targetSelector: '[data-action-card="artifact:toggle"], [data-action-tab="toggle"]',
        titleKey: 'guided-tour.step.enable-artifact-toggle.title',
        titleFallback: '开启法宝启用状态',
        bodyKey: 'guided-tour.step.enable-artifact-toggle.body',
        bodyFallback: '法宝每息消耗基础灵力的 10% 维持；启用期间每息累积 1 层「盈能」。',
        placement: 'left',
        advanceMode: 'target-click',
        prepare: OPEN_ACTION_TOGGLE_PREPARE,
      },
      {
        id: 'ignore-obstacles-fly',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.ignore-obstacles-fly.title',
        titleFallback: '无视地形飞行',
        bodyKey: 'guided-tour.step.ignore-obstacles-fly.body',
        bodyFallback: '巡天飞剑启用时，角色可直接穿行原本无法通过的悬崖、水面与岩石障碍，大幅提升跑图速度。',
        placement: 'top',
      },
    ],
  },
  {
    id: 'sect-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.sect.title',
    titleFallback: '宗门领地·护宗大阵',
    summaryFallback: '掌握申请加入与创建宗门、领地扩展、护宗大阵灵力维护与防御。',
    steps: [
      {
        id: 'open-sect-panel',
        targetSelector: '#hud-open-sect, [data-hud-sect]',
        titleKey: 'guided-tour.step.open-sect-panel.title',
        titleFallback: '打开宗门界面',
        bodyKey: 'guided-tour.step.open-sect-panel.body',
        bodyFallback: '点击左上角快捷入口进入宗门管理界面。',
        placement: 'bottom',
        advanceMode: 'target-click',
      },
      {
        id: 'sect-list-or-create',
        targetSelector: '[data-action-card="sect:manage"], #pane-action',
        titleKey: 'guided-tour.step.sect-list-or-create.title',
        titleFallback: '申请入宗或创建宗门',
        bodyKey: 'guided-tour.step.sect-list-or-create.body',
        bodyFallback: '宗门拥有独立的专属领地地图、职位权限体系与领地防御。',
        placement: 'left',
      },
      {
        id: 'expand-territory',
        targetSelector: '.sect-territory-map, [data-sect-territory]' ,
        titleKey: 'guided-tour.step.expand-territory.title',
        titleFallback: '攻打地块扩展领地',
        bodyKey: 'guided-tour.step.expand-territory.body',
        bodyFallback: '通过击败地块怪将领地向外扩展，每次扩张 8 格。',
        placement: 'top',
      },
      {
        id: 'sect-defense-array',
        targetSelector: '#pane-action',
        titleKey: 'guided-tour.step.sect-defense-array.title',
        titleFallback: '护宗大阵灵力维护',
        bodyKey: 'guided-tour.step.sect-defense-array.body',
        bodyFallback: '护宗大阵提供边界屏障与领地内减伤；投入灵石充能以维持大阵运转天数。',
        placement: 'left',
      },
    ],
  },
  {
    id: 'dungeon-instance-guide',
    category: 'gameplay',
    storageVersion: 1,
    autoStart: false,
    titleKey: 'guided-tour.flow.dungeon.title',
    titleFallback: '秘境副本·首领挑战',
    summaryFallback: '了解进阶副本机制、环境词缀克制、Boss 破招打断与通关结算。',
    steps: [
      {
        id: 'dungeon-portal',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.dungeon-portal.title',
        titleFallback: '进入秘境入口',
        bodyKey: 'guided-tour.step.dungeon-portal.body',
        bodyFallback: '组队或单人踏入秘境传送阵。',
        placement: 'top',
      },
      {
        id: 'dungeon-mechanic-alert',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.dungeon-mechanic-alert.title',
        titleFallback: '应对环境词缀与机关',
        bodyKey: 'guided-tour.step.dungeon-mechanic-alert.body',
        bodyFallback: '秘境具有五行狂暴或毒雾等词缀，需利用地形与解法机制克制。',
        placement: 'top',
      },
      {
        id: 'boss-phase-break',
        targetSelector: '#game-stage',
        titleKey: 'guided-tour.step.boss-phase-break.title',
        titleFallback: '首领破防与化解',
        bodyKey: 'guided-tour.step.boss-phase-break.body',
        bodyFallback: 'Boss 释放大招前有地面预警前摇，通过破招削弱 Boss 护体灵力，输出翻倍。',
        placement: 'top',
      },
      {
        id: 'dungeon-settlement',
        targetSelector: '.dungeon-summary-modal, #hud',
        titleKey: 'guided-tour.step.dungeon-settlement.title',
        titleFallback: '通关结算与掉落',
        bodyKey: 'guided-tour.step.dungeon-settlement.body',
        bodyFallback: '全队根据贡献度结算专属战利品与功德奖励。',
        placement: 'top',
      },
    ],
  },
];

export function getGuidedTourFlowById(flowId: string): GuidedTourFlow | undefined {
  return GUIDED_TOUR_FLOWS.find((f) => f.id === flowId);
}

export function getGuidedTourFlowsByCategory(category: GuidedTourCategory): GuidedTourFlow[] {
  return GUIDED_TOUR_FLOWS.filter((f) => f.category === category);
}
