import { TileType } from '../../types';
import {
  HOUSE_DECOR_TILE_BG_COLORS,
  HOUSE_DECOR_TILE_GLYPHS,
  HOUSE_DECOR_TILE_GLYPH_COLORS,
} from '../gameplay/house-terrain';

/**
 * 地形文字渲染视觉常量。
 */

/** 地形底色映射。 */
export const TILE_VISUAL_BG_COLORS: Record<TileType, string> = {
  [TileType.Floor]: '#ddd8cf',
  [TileType.Road]: '#cdb89c',
  [TileType.Trail]: '#b4946f',
  [TileType.Wall]: '#3e3a35',
  [TileType.Door]: '#8b7355',
  [TileType.Window]: '#8bb6cf',
  [TileType.BrokenWindow]: '#9aa7b0',
  [TileType.Portal]: '#5c3d7a',
  [TileType.Stairs]: '#7f5a34',
  [TileType.Grass]: '#b8c98b',
  [TileType.Hill]: '#b7a17f',
  [TileType.Cliff]: '#5a514a',
  [TileType.Mud]: '#8b6a4c',
  [TileType.Swamp]: '#556b3f',
  [TileType.ColdBog]: '#4f6775',
  [TileType.MoltenPool]: '#8e3d20',
  [TileType.Water]: '#6e9ab8',
  [TileType.Cloud]: '#d9e4f2',
  [TileType.CloudFloor]: '#edf3fb',
  [TileType.Void]: '#171b31',
  [TileType.Tree]: '#4d6b3a',
  [TileType.Bamboo]: '#3f7a46',
  [TileType.Stone]: '#7a7570',
  [TileType.SpiritOre]: '#4b5f87',
  [TileType.BlackIronOre]: '#4f5967',
  [TileType.BrokenSwordHeap]: '#6a5b52',
  ...HOUSE_DECOR_TILE_BG_COLORS,
};

/** 地形字符映射。 */
export const TILE_VISUAL_GLYPHS: Record<TileType, string> = {
  [TileType.Floor]: '·',
  [TileType.Road]: '路',
  [TileType.Trail]: '径',
  [TileType.Wall]: '▓',
  [TileType.Door]: '门',
  [TileType.Window]: '窗',
  [TileType.BrokenWindow]: '裂',
  [TileType.Portal]: '阵',
  [TileType.Stairs]: '阶',
  [TileType.Grass]: ',',
  [TileType.Hill]: '坡',
  [TileType.Cliff]: '崖',
  [TileType.Mud]: '泥',
  [TileType.Swamp]: '沼',
  [TileType.ColdBog]: '寒',
  [TileType.MoltenPool]: '熔',
  [TileType.Water]: '水',
  [TileType.Cloud]: '云',
  [TileType.CloudFloor]: '云',
  [TileType.Void]: '空',
  [TileType.Tree]: '木',
  [TileType.Bamboo]: '竹',
  [TileType.Stone]: '石',
  [TileType.SpiritOre]: '灵',
  [TileType.BlackIronOre]: '铁',
  [TileType.BrokenSwordHeap]: '刃',
  ...HOUSE_DECOR_TILE_GLYPHS,
};

/** 地形字符颜色映射。 */
export const TILE_VISUAL_GLYPH_COLORS: Record<TileType, string> = {
  [TileType.Floor]: 'rgba(0,0,0,0.15)',
  [TileType.Road]: 'rgba(90,55,24,0.35)',
  [TileType.Trail]: 'rgba(84,52,28,0.42)',
  [TileType.Wall]: 'rgba(255,255,255,0.2)',
  [TileType.Door]: '#f0e0c0',
  [TileType.Window]: '#e6f8ff',
  [TileType.BrokenWindow]: '#d8dde2',
  [TileType.Portal]: '#d0b0f0',
  [TileType.Stairs]: '#f3d19c',
  [TileType.Grass]: 'rgba(50,80,30,0.2)',
  [TileType.Hill]: 'rgba(92,60,32,0.36)',
  [TileType.Cliff]: 'rgba(245,240,232,0.28)',
  [TileType.Mud]: 'rgba(250,240,220,0.34)',
  [TileType.Swamp]: 'rgba(220,240,180,0.4)',
  [TileType.ColdBog]: '#d5eefc',
  [TileType.MoltenPool]: '#ffd0a1',
  [TileType.Water]: 'rgba(30,50,80,0.4)',
  [TileType.Cloud]: 'rgba(82,97,132,0.32)',
  [TileType.CloudFloor]: 'rgba(118,138,182,0.22)',
  [TileType.Void]: '#98a0db',
  [TileType.Tree]: 'rgba(20,40,15,0.5)',
  [TileType.Bamboo]: 'rgba(16,54,20,0.56)',
  [TileType.Stone]: 'rgba(40,35,30,0.35)',
  [TileType.SpiritOre]: '#d2e7ff',
  [TileType.BlackIronOre]: '#d7deea',
  [TileType.BrokenSwordHeap]: '#f0d3b0',
  ...HOUSE_DECOR_TILE_GLYPH_COLORS,
};
