import { NEXT_S2C, type NEXT_S2C_EventPayload } from '@mud/shared-next';
import type { SocketManager } from './network/socket';

type MainLowFrequencySocketBindingsOptions = {
  socket: Pick<SocketManager, 'on' | 'onKick' | 'onConnectError' | 'onDisconnect'>;
  onLootWindowUpdate: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.LootWindowUpdate>) => void;
  onTileDetail: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.TileDetail>) => void;
  onDetail: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Detail>) => void;
  onAttrDetail: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.AttrDetail>) => void;
  onAlchemyPanel: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.AlchemyPanel>) => void;
  onEnhancementPanel: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.EnhancementPanel>) => void;
  onLeaderboard: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Leaderboard>) => void;
  onWorldSummary: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.WorldSummary>) => void;
  onNpcQuests: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.NpcQuests>) => void;
  onQuests: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Quests>) => void;
  onQuestNavigateResult: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.QuestNavigateResult>) => void;
  onSuggestionUpdate: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.SuggestionUpdate>) => void;
  onMailSummary: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MailSummary>) => void;
  onMailPage: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MailPage>) => void;
  onMailDetail: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MailDetail>) => void;
  onRedeemCodesResult: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.RedeemCodesResult>) => void;
  onMailOpResult: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MailOpResult>) => void;
  onMarketUpdate: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketUpdate>) => void;
  onMarketListings: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketListings>) => void;
  onMarketOrders: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketOrders>) => void;
  onMarketStorage: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketStorage>) => void;
  onMarketItemBook: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketItemBook>) => void;
  onMarketTradeHistory: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.MarketTradeHistory>) => void;
  onNpcShop: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.NpcShop>) => void;
  onNotice: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Notice>) => void;
  onError: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Error>) => void;
  onKick: Parameters<SocketManager['onKick']>[0];
  onConnectError: Parameters<SocketManager['onConnectError']>[0];
  onDisconnect: Parameters<SocketManager['onDisconnect']>[0];
  onPong: (data: NEXT_S2C_EventPayload<typeof NEXT_S2C.Pong>) => void;
};

export function bindMainLowFrequencySocketEvents(options: MainLowFrequencySocketBindingsOptions): void {
  options.socket.on(NEXT_S2C.LootWindowUpdate, options.onLootWindowUpdate);
  options.socket.on(NEXT_S2C.TileDetail, options.onTileDetail);
  options.socket.on(NEXT_S2C.Detail, options.onDetail);
  options.socket.on(NEXT_S2C.AttrDetail, options.onAttrDetail);
  options.socket.on(NEXT_S2C.AlchemyPanel, options.onAlchemyPanel);
  options.socket.on(NEXT_S2C.EnhancementPanel, options.onEnhancementPanel);
  options.socket.on(NEXT_S2C.Leaderboard, options.onLeaderboard);
  options.socket.on(NEXT_S2C.WorldSummary, options.onWorldSummary);
  options.socket.on(NEXT_S2C.NpcQuests, options.onNpcQuests);
  options.socket.on(NEXT_S2C.Quests, options.onQuests);
  options.socket.on(NEXT_S2C.QuestNavigateResult, options.onQuestNavigateResult);
  options.socket.on(NEXT_S2C.SuggestionUpdate, options.onSuggestionUpdate);
  options.socket.on(NEXT_S2C.MailSummary, options.onMailSummary);
  options.socket.on(NEXT_S2C.MailPage, options.onMailPage);
  options.socket.on(NEXT_S2C.MailDetail, options.onMailDetail);
  options.socket.on(NEXT_S2C.RedeemCodesResult, options.onRedeemCodesResult);
  options.socket.on(NEXT_S2C.MailOpResult, options.onMailOpResult);
  options.socket.on(NEXT_S2C.MarketUpdate, options.onMarketUpdate);
  options.socket.on(NEXT_S2C.MarketListings, options.onMarketListings);
  options.socket.on(NEXT_S2C.MarketOrders, options.onMarketOrders);
  options.socket.on(NEXT_S2C.MarketStorage, options.onMarketStorage);
  options.socket.on(NEXT_S2C.MarketItemBook, options.onMarketItemBook);
  options.socket.on(NEXT_S2C.MarketTradeHistory, options.onMarketTradeHistory);
  options.socket.on(NEXT_S2C.NpcShop, options.onNpcShop);
  options.socket.on(NEXT_S2C.Notice, options.onNotice);
  options.socket.on(NEXT_S2C.Error, options.onError);
  options.socket.onKick(options.onKick);
  options.socket.onConnectError(options.onConnectError);
  options.socket.onDisconnect(options.onDisconnect);
  options.socket.on(NEXT_S2C.Pong, options.onPong);
}
