/** 威胁箭头可视化颜色配置常量。 */
export const SELF_THREAT_ARROW_COLOR = 'rgba(186, 244, 198, 0.98)';
/** SELF_THREAT_ARROW_GLOW：自身THREAT ARROW GLOW。 */
export const SELF_THREAT_ARROW_GLOW = 'rgba(118, 206, 142, 0.48)';

/** OTHER_THREAT_ARROW_COLOR：OTHER THREAT ARROW颜色。 */
export const OTHER_THREAT_ARROW_COLOR = 'rgba(255, 92, 92, 0.98)';
/** OTHER_THREAT_ARROW_GLOW：OTHER THREAT ARROW GLOW。 */
export const OTHER_THREAT_ARROW_GLOW = 'rgba(236, 38, 38, 0.46)';



