import type { NumericRatioDivisors, NumericStats } from './numeric';
import type { ActionDef } from './action-combat-types';
import type { AutoBattleSkillConfig, AutoBattleTargetingMode, AutoUsePillConfig, CombatTargetingRules } from './automation-types';
import type { BodyTrainingState, HeavenGateRootValues, HeavenGateState, PlayerRealmState, TechniqueState } from './cultivation-types';
import type { AlchemySkillState, PlayerAlchemyJob, PlayerAlchemyPreset, PlayerEnhancementJob, PlayerEnhancementRecord } from './crafting-types';
import type { EquipmentSlots, Inventory } from './item-runtime-types';
import type { MarketStorage } from './market-types';
import type { PendingLogbookMessage, QuestNavigationState, QuestState } from './quest-types';
import type { TemporaryBuffState } from './skill-types';
import type { AttrBonus, Attributes } from './attribute-types';
import type { Direction } from './world-core-types';

/** 玩家状态。 */
export interface PlayerState {
  id: string;
  name: string;
  displayName?: string;
  isBot?: boolean;
  online?: boolean;
  inWorld?: boolean;
  lastHeartbeatAt?: number;
  offlineSinceAt?: number;
  senseQiActive?: boolean;
  autoRetaliate?: boolean;
  autoBattleStationary?: boolean;
  allowAoePlayerHit?: boolean;
  autoIdleCultivation?: boolean;
  autoSwitchCultivation?: boolean;
  cultivationActive?: boolean;
  realmLv?: number;
  realmName?: string;
  realmStage?: string;
  realmReview?: string;
  breakthroughReady?: boolean;
  heavenGate?: HeavenGateState | null;
  spiritualRoots?: HeavenGateRootValues | null;
  boneAgeBaseYears?: number;
  lifeElapsedTicks?: number;
  lifespanYears?: number | null;
  mapId: string;
  x: number;
  y: number;
  facing: Direction;
  viewRange: number;
  hp: number;
  maxHp: number;
  qi: number;
  dead: boolean;
  foundation?: number;
  combatExp?: number;
  baseAttrs: Attributes;
  bonuses: AttrBonus[];
  temporaryBuffs?: TemporaryBuffState[];
  finalAttrs?: Attributes;
  numericStats?: NumericStats;
  ratioDivisors?: NumericRatioDivisors;
  inventory: Inventory;
  marketStorage?: MarketStorage;
  equipment: EquipmentSlots;
  techniques: TechniqueState[];
  bodyTraining?: BodyTrainingState;
  actions: ActionDef[];
  quests: QuestState[];
  autoBattle: boolean;
  autoBattleSkills: AutoBattleSkillConfig[];
  autoUsePills: AutoUsePillConfig[];
  combatTargetingRules?: CombatTargetingRules;
  autoBattleTargetingMode: AutoBattleTargetingMode;
  combatTargetId?: string;
  combatTargetLocked?: boolean;
  cultivatingTechId?: string;
  pendingLogbookMessages?: PendingLogbookMessage[];
  idleTicks?: number;
  revealedBreakthroughRequirementIds?: string[];
  unlockedMinimapIds?: string[];
  realm?: PlayerRealmState;
  questNavigation?: QuestNavigationState;
  questCrossMapNavCooldownUntilLifeTicks?: number;
  alchemySkill?: AlchemySkillState;
  gatherSkill?: AlchemySkillState;
  alchemyPresets?: PlayerAlchemyPreset[];
  alchemyJob?: PlayerAlchemyJob | null;
  enhancementSkill?: AlchemySkillState;
  enhancementSkillLevel?: number;
  enhancementJob?: PlayerEnhancementJob | null;
  enhancementRecords?: PlayerEnhancementRecord[];
}
