/**
 * 地图地形与耐久常量导出。
 */

export {
  DEFAULT_TERRAIN_DURABILITY_BY_TILE,
  LEGACY_MAP_TERRAIN_PROFILE_IDS,
  SPECIAL_TILE_DURABILITY_MULTIPLIERS,
  SPECIAL_TILE_RESTORE_SPEED_MULTIPLIERS,
  TERRAIN_DURABILITY_PROFILES,
  type TerrainDurabilityProfileId,
  type TerrainDurabilityProfile,
} from './map';
