/**
 * 本文件负责服务端运行配置的解析或角色判断，是启动期配置边界的一部分。
 *
 * 维护时要让默认值对生产环境友好，并避免把临时本地配置误当作线上真源。
 */
/**
 * GM 运行时环境变量文件读写工具。
 *
 * `.runtime/server.local.env` 作为 GM 可持久化的本地运行时覆盖层，
 * 由 GM 环境变量管理页写入，并可在启动期或运行期覆盖 process.env。
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

import { resolveProjectPath } from '../common/project-path';

export const RUNTIME_ENV_FILE_PATH = resolveProjectPath('.runtime', 'server.local.env');

/** 判断是否是合法 env key。 */
export function isValidEnvKey(key: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key);
}

/** 去除值两端引号（单引号或双引号包裹）。 */
function normalizeEnvValue(rawValue: string): string {
  const trimmed = rawValue.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return trimmed.slice(1, -1).replace(/\\"/gu, '"').replace(/\\\\/gu, '\\');
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1).replace(/\\'/gu, "'").replace(/\\\\/gu, '\\');
  }
  return trimmed;
}

/** 解析 .env 文本为 key-value map，跳过注释和空行。 */
export function parseEnvText(content: string): Map<string, string> {
  const entries = new Map<string, string>();
  for (const rawLine of content.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const normalized = line.startsWith('export ') ? line.slice('export '.length).trim() : line;
    const separatorIndex = normalized.indexOf('=');
    if (separatorIndex <= 0) continue;

    const key = normalized.slice(0, separatorIndex).trim();
    if (!isValidEnvKey(key)) continue;

    const value = normalizeEnvValue(normalized.slice(separatorIndex + 1));
    entries.set(key, value);
  }
  return entries;
}

/** 读取 runtime env 文件。 */
export function readRuntimeEnvFile(filePath = RUNTIME_ENV_FILE_PATH): Map<string, string> {
  if (!fs.existsSync(filePath)) {
    return new Map();
  }
  return parseEnvText(fs.readFileSync(filePath, 'utf8'));
}

/** 将值序列化为单行 .env 值。 */
function serializeEnvValue(value: string): string {
  if (value === '') return '""';
  if (/^[A-Za-z0-9_./:@,+\-=]+$/u.test(value)) return value;
  return `"${value.replace(/\\/gu, '\\\\').replace(/"/gu, '\\"')}"`;
}

/** 写回 runtime env 文件。 */
export function writeRuntimeEnvFile(entries: Map<string, string>, filePath = RUNTIME_ENV_FILE_PATH): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const rows = [...entries.entries()]
    .filter(([key]) => isValidEnvKey(key))
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${serializeEnvValue(value)}`);

  const header = [
    '# GM runtime environment overlay.',
    '# This file is generated by the GM environment manager.',
    '# Values here are applied as runtime overrides where supported.',
  ].join('\n');
  fs.writeFileSync(filePath, `${header}\n${rows.join('\n')}\n`, 'utf8');
}

/** 更新一个 runtime env 文件项。 */
export function upsertRuntimeEnvFileEntry(key: string, value: string, filePath = RUNTIME_ENV_FILE_PATH): Map<string, string> {
  const entries = readRuntimeEnvFile(filePath);
  entries.set(key, value);
  writeRuntimeEnvFile(entries, filePath);
  return entries;
}

/** 删除一个 runtime env 文件项。 */
export function deleteRuntimeEnvFileEntry(key: string, filePath = RUNTIME_ENV_FILE_PATH): Map<string, string> {
  const entries = readRuntimeEnvFile(filePath);
  entries.delete(key);
  writeRuntimeEnvFile(entries, filePath);
  return entries;
}

/** 把给定 env map 应用到当前 process.env。 */
export function applyEnvEntriesToProcess(entries: Map<string, string>, overwrite: boolean): number {
  let applied = 0;
  for (const [key, value] of entries) {
    if (!isValidEnvKey(key)) continue;
    if (!overwrite && typeof process.env[key] === 'string' && process.env[key]?.trim() !== '') {
      continue;
    }
    process.env[key] = value;
    applied += 1;
  }
  return applied;
}

/** 从 runtime env 文件加载到当前 process.env。 */
export function applyRuntimeEnvFileToProcess(filePath = RUNTIME_ENV_FILE_PATH, overwrite = true): number {
  return applyEnvEntriesToProcess(readRuntimeEnvFile(filePath), overwrite);
}
