/** 怪物相关常量定义文件。 */
export const MONSTER_RESPAWN_ACCELERATION_BASE_PERCENT = 100;
/** MONSTER_RESPAWN_ACCELERATION_STEP_PERCENT：定义该变量以承载业务值。 */
export const MONSTER_RESPAWN_ACCELERATION_STEP_PERCENT = 100;
/** MONSTER_RESPAWN_ACCELERATION_MAX_PERCENT：定义该变量以承载业务值。 */
export const MONSTER_RESPAWN_ACCELERATION_MAX_PERCENT = 1000;
/** MONSTER_LOST_SIGHT_CHASE_TICKS：定义该变量以承载业务值。 */
export const MONSTER_LOST_SIGHT_CHASE_TICKS = 3;
/** ORDINARY_MONSTER_SPAWN_COUNT：定义该变量以承载业务值。 */
export const ORDINARY_MONSTER_SPAWN_COUNT = 4;
/** ORDINARY_MONSTER_SPAWN_MAX_ALIVE：定义该变量以承载业务值。 */
export const ORDINARY_MONSTER_SPAWN_MAX_ALIVE = 6;
/** ORDINARY_MONSTER_OVERLEVEL_SPIRIT_STONE_DROP_THRESHOLD：定义该变量以承载业务值。 */
export const ORDINARY_MONSTER_OVERLEVEL_SPIRIT_STONE_DROP_THRESHOLD = 1;
/** ORDINARY_MONSTER_OVERLEVEL_SPIRIT_STONE_DROP_MULTIPLIER：定义该变量以承载业务值。 */
export const ORDINARY_MONSTER_OVERLEVEL_SPIRIT_STONE_DROP_MULTIPLIER = 0.7;
