export const MARKET_CURRENCY_ITEM_ID = 'spirit_stone';
export const MARKET_MAX_ORDER_QUANTITY = 999_900_000_000;
export const MARKET_TRADE_HISTORY_VISIBLE_LIMIT = 100;
export const MARKET_TRADE_HISTORY_PAGE_SIZE = 10;
