export const MONSTER_RESPAWN_ACCELERATION_BASE_PERCENT = 100;
export const MONSTER_RESPAWN_ACCELERATION_STEP_PERCENT = 100;
export const MONSTER_RESPAWN_ACCELERATION_MAX_PERCENT = 1000;
export const ORDINARY_MONSTER_SPAWN_COUNT = 4;
export const ORDINARY_MONSTER_SPAWN_MAX_ALIVE = 6;
